// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: my_lvgl

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"
#include "../ui.h"

// 相册按钮事件
void on_btnAlbum_clicked(lv_event_t * e);
void on_btnBack_clicked(lv_event_t * e);
void on_btnPrev_clicked(lv_event_t * e);
void on_btnNext_clicked(lv_event_t * e);
void on_btnDelete_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
