// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: my_lvgl

#include "../ui.h"

lv_obj_t * ui_ScreenAlbum = NULL;
lv_obj_t * ui_imgPhotoPreview = NULL;
lv_obj_t * ui_btnPrev = NULL;
lv_obj_t * ui_btnNext = NULL;
lv_obj_t * ui_btnDelete = NULL;
lv_obj_t * ui_btnBack = NULL;
lv_obj_t * ui_lblPhotoInfo = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label11 = NULL;
// event funtions

// build funtions

void ui_ScreenAlbum_screen_init(void)
{
    ui_ScreenAlbum = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgPhotoPreview = lv_img_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_imgPhotoPreview, lv_pct(80));
    lv_obj_set_height(ui_imgPhotoPreview, lv_pct(80));
    lv_obj_set_align(ui_imgPhotoPreview, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgPhotoPreview, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgPhotoPreview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnPrev = lv_btn_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_btnPrev, 100);
    lv_obj_set_height(ui_btnPrev, 50);
    lv_obj_set_x(ui_btnPrev, -347);
    lv_obj_set_y(ui_btnPrev, 212);
    lv_obj_set_align(ui_btnPrev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnNext = lv_btn_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_btnNext, 100);
    lv_obj_set_height(ui_btnNext, 50);
    lv_obj_set_x(ui_btnNext, 347);
    lv_obj_set_y(ui_btnNext, 212);
    lv_obj_set_align(ui_btnNext, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnDelete = lv_btn_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_btnDelete, 100);
    lv_obj_set_height(ui_btnDelete, 50);
    lv_obj_set_x(ui_btnDelete, 0);
    lv_obj_set_y(ui_btnDelete, 212);
    lv_obj_set_align(ui_btnDelete, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDelete, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnDelete, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBack = lv_btn_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_btnBack, 100);
    lv_obj_set_height(ui_btnBack, 50);
    lv_obj_set_x(ui_btnBack, -343);
    lv_obj_set_y(ui_btnBack, -212);
    lv_obj_set_align(ui_btnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblPhotoInfo = lv_label_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_lblPhotoInfo, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(ui_lblPhotoInfo, LV_SIZE_CONTENT);    /// 3
    lv_obj_set_x(ui_lblPhotoInfo, 0);
    lv_obj_set_y(ui_lblPhotoInfo, -205);
    lv_obj_set_align(ui_lblPhotoInfo, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -349);
    lv_obj_set_y(ui_Label8, 212);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "prev");

    ui_Label9 = lv_label_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 346);
    lv_obj_set_y(ui_Label9, 213);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "next");

    ui_Label10 = lv_label_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, 212);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "delete");

    ui_Label11 = lv_label_create(ui_ScreenAlbum);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -344);
    lv_obj_set_y(ui_Label11, -213);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "back");

}

void ui_ScreenAlbum_screen_destroy(void)
{
    if(ui_ScreenAlbum) lv_obj_del(ui_ScreenAlbum);

    // NULL screen variables
    ui_ScreenAlbum = NULL;
    ui_imgPhotoPreview = NULL;
    ui_btnPrev = NULL;
    ui_btnNext = NULL;
    ui_btnDelete = NULL;
    ui_btnBack = NULL;
    ui_lblPhotoInfo = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;

}
