// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: my_lvgl

#include "../ui.h"

lv_obj_t * uic_BtnAlbum;
lv_obj_t * uic_Image1;
lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_ImgPreview = NULL;
lv_obj_t * ui_BtnAlbum = NULL;
lv_obj_t * ui_Container = NULL;
lv_obj_t * ui_LabelNet = NULL;
lv_obj_t * ui_LabelRecStatus = NULL;
lv_obj_t * ui_LabelStorage = NULL;
lv_obj_t * ui_LabelGps = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImgPreview = lv_img_create(ui_ScreenMain);
    lv_obj_set_width(ui_ImgPreview, lv_pct(100));
    lv_obj_set_height(ui_ImgPreview, lv_pct(100));
    lv_obj_set_x(ui_ImgPreview, 1);
    lv_obj_set_y(ui_ImgPreview, 0);
    lv_obj_set_align(ui_ImgPreview, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgPreview, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgPreview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BtnAlbum = lv_btn_create(ui_ScreenMain);
    lv_obj_set_width(ui_BtnAlbum, 100);
    lv_obj_set_height(ui_BtnAlbum, 50);
    lv_obj_set_x(ui_BtnAlbum, -318);
    lv_obj_set_y(ui_BtnAlbum, 191);
    lv_obj_set_align(ui_BtnAlbum, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnAlbum, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnAlbum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_Container);
    lv_obj_set_width(ui_Container, 209);
    lv_obj_set_height(ui_Container, 144);
    lv_obj_set_x(ui_Container, 289);
    lv_obj_set_y(ui_Container, -164);
    lv_obj_set_align(ui_Container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNet = lv_label_create(ui_Container);
    lv_obj_set_width(ui_LabelNet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNet, -38);
    lv_obj_set_y(ui_LabelNet, -52);
    lv_obj_set_align(ui_LabelNet, LV_ALIGN_CENTER);

    ui_LabelRecStatus = lv_label_create(ui_Container);
    lv_obj_set_width(ui_LabelRecStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRecStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRecStatus, -38);
    lv_obj_set_y(ui_LabelRecStatus, -14);
    lv_obj_set_align(ui_LabelRecStatus, LV_ALIGN_CENTER);

    ui_LabelStorage = lv_label_create(ui_Container);
    lv_obj_set_width(ui_LabelStorage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStorage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStorage, -38);
    lv_obj_set_y(ui_LabelStorage, 20);
    lv_obj_set_align(ui_LabelStorage, LV_ALIGN_CENTER);

    ui_LabelGps = lv_label_create(ui_Container);
    lv_obj_set_width(ui_LabelGps, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelGps, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelGps, -38);
    lv_obj_set_y(ui_LabelGps, 55);
    lv_obj_set_align(ui_LabelGps, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_ScreenMain);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -317);
    lv_obj_set_y(ui_Label7, 192);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Album");

    uic_Image1 = ui_ImgPreview;
    uic_BtnAlbum = ui_BtnAlbum;

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    uic_Image1 = NULL;
    ui_ImgPreview = NULL;
    uic_BtnAlbum = NULL;
    ui_BtnAlbum = NULL;
    ui_Container = NULL;
    ui_LabelNet = NULL;
    ui_LabelRecStatus = NULL;
    ui_LabelStorage = NULL;
    ui_LabelGps = NULL;
    ui_Label7 = NULL;

}
