// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: my_lvgl

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_ImgPreview;
extern lv_obj_t * ui_BtnAlbum;
extern lv_obj_t * ui_Container;
extern lv_obj_t * ui_LabelNet;
extern lv_obj_t * ui_LabelRecStatus;
extern lv_obj_t * ui_LabelStorage;
extern lv_obj_t * ui_LabelGps;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Image1;
extern lv_obj_t * uic_BtnAlbum;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

