// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: my_lvgl

#ifndef UI_SCREENALBUM_H
#define UI_SCREENALBUM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAlbum
extern void ui_ScreenAlbum_screen_init(void);
extern void ui_ScreenAlbum_screen_destroy(void);
extern lv_obj_t * ui_ScreenAlbum;
extern lv_obj_t * ui_imgPhotoPreview;
extern lv_obj_t * ui_btnPrev;
extern lv_obj_t * ui_btnNext;
extern lv_obj_t * ui_btnDelete;
extern lv_obj_t * ui_btnBack;
extern lv_obj_t * ui_lblPhotoInfo;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

